import Navbar from "@/components/shared/Navbar";

export const metadata = {
  title: "Terms of Service — VibeCheck",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      <div className="absolute inset-0 rpg-grid opacity-10 pointer-events-none" />
      <div className="absolute inset-0 dungeon-gradient pointer-events-none" />
      <div className="scanline" />
      
      <Navbar />
      <main className="pt-40 pb-24 px-4 relative z-10">
        <article className="prose prose-neutral dark:prose-invert max-w-2xl mx-auto rpg-panel p-8 md:p-12 bg-indigo-950/20">
          <h1 className="font-mono text-3xl font-bold uppercase tracking-tight text-foreground glow-text-magenta mb-2">Terms of Service</h1>
          <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground mb-8">Last updated: March 13, 2026</p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">1. Acceptance of terms</h2>
          <p className="text-sm text-muted-foreground mb-6">
            By accessing or using VibeCheck (&quot;the Service&quot;), you agree
            to be bound by these Terms of Service. If you do not agree, do not
            use the Service.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">2. Description of service</h2>
          <p className="text-sm text-muted-foreground mb-6">
            VibeCheck is an automated code auditing tool that analyzes public
            GitHub repositories or uploaded ZIP files and generates a report of
            findings. The Service is provided &quot;as is&quot; and is not a
            substitute for professional security auditing or code review.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">3. User responsibilities</h2>
          <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground mb-6">
            <li>
              You may only submit repositories and code that you have the right
              to analyze.
            </li>
            <li>
              You must not use the Service to attack, scan, or probe systems you
              do not own or have authorization to test.
            </li>
            <li>
              You must not attempt to circumvent rate limits or abuse the
              Service.
            </li>
          </ul>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">4. Intellectual property</h2>
          <p className="text-sm text-muted-foreground mb-6">
            You retain all rights to your code. VibeCheck does not claim
            ownership of any code you submit for analysis. Audit reports
            generated by the Service are yours to use and share.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">5. Disclaimers</h2>
          <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground mb-6">
            <li>
              The Service is provided &quot;as is&quot; without warranties of
              any kind, express or implied.
            </li>
            <li>
              Audit results are automated and may contain false positives or miss
              issues. They should not be relied upon as the sole measure of code
              quality or security.
            </li>
            <li>
              VibeCheck is not liable for any damages arising from use of the
              Service or reliance on audit results.
            </li>
          </ul>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">6. Usage limits</h2>
          <p className="text-sm text-muted-foreground mb-6">
            Free accounts are subject to usage limits as described on the
            Pricing page. We reserve the right to throttle or suspend accounts
            that abuse the Service.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">7. Termination</h2>
          <p className="text-sm text-muted-foreground mb-6">
            We may suspend or terminate your access to the Service at any time,
            with or without cause. You may stop using the Service at any time.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">8. Changes to terms</h2>
          <p className="text-sm text-muted-foreground mb-6">
            We may update these terms from time to time. Continued use of the
            Service after changes constitutes acceptance of the new terms.
          </p>

          <h2 className="font-mono text-xl font-bold uppercase tracking-tight text-foreground mt-8 mb-4">9. Contact</h2>
          <p className="text-sm text-muted-foreground">
            Questions about these terms? Contact us at{" "}
            <a href="mailto:leonardo.j.ramirez@regainflow.com" className="text-magenta hover:underline">leonardo.j.ramirez@regainflow.com</a>.
          </p>
        </article>
      </main>
    </div>
  );
}
